### PR TITLE
Remove trailing commas.

### PR DESCRIPTION
**Pull request by mattcollier**

### CODE REVIEW

**Comment by dunglas** [comment]
Why? Trailing comma make diff easier to read.

**Comment by mattcollier** [comment]
@dunglas porting this code over the nodejs.  The extra commas in object declarations are a matter of style, but this one throws a `Synatax Error: Unexpected token` with nodejs:

https://github.com/dunglas/api-doc-parser/blob/master/src/hydra/parseHydraDocumentation.js#L129

**Comment by dunglas** [comment]
Weird, we use this code in Node (e.g.: https://github.com/api-platform/generate-crud) but by default NPM will load the compiled version.

**Comment by mysiar** [comment]
this is solved https://github.com/api-platform/api-doc-parser/commit/0a605d965ea80cab63533df8ed95924fc7f3f3d5

**Pull request closed without merging**
